mcp:
  enabled: true

spring:
  application:
    name: mcp-sample-server
  main:
    web-application-type: none
    banner-mode: off

logging:
  pattern:
    console: "%msg%n"
  file:
    name: mcp-server.log
  level:
    io.modelcontextprotocol: DEBUG
    com.github.star.mcp: DEBUG
