
server:
  port: 9231

mcp:
  enabled: true
  base-path: /mcp
  expose-api: true
  streaming-enabled: true

spring:
  application:
    name: mcp-sample-server

spring.ai.mcp.server:
  stdio: true
  enabled: true

logging:
  level:
    com.github.star.mcp: DEBUG
